[window]
# opacity = 0.74
opacity = 0.8
# opacity = 0.84
# opacity = 0.88
# opacity = 0.93
decorations = "None"
# startup_mode = "Maximized"
# startup_mode = "SimpleFullscreen"

[window.padding]
x = 8
y = 8

[font]
# size = 13.5
size = 12

[font.normal]
family = "Hurmit Nerd Font"
style = "Regular"

[font.bold]
family = "Hurmit Nerd Font"
style = "Bold"

[font.italic]
family = "Hurmit Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Hurmit Nerd Font"
style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = true

[colors.normal]
black = "#181818"
red = "#f44336"
green = "#64dd17"
yellow = "#ffc107"
blue = "#2196f3"
magenta = "#e91e63"
cyan = "#f57c00"
white = "#e0e0e0"

[colors.bright]
black = "#424242"
red = "#e57373"
green = "#00e613"
yellow = "#ffca28"
blue = "#29b6f6"
magenta = "#ec407a"
cyan = "#ff9800"
white = "#f5f5f5"
